In [13]:
from random import random
from random import randint
from random import choice
from numpy import array
from numpy import zeros
import numpy as np

In [26]:
def check_in_frame ( size, pos ):
    if 0 <= pos[0] < size and  0 <= pos[1] < size:
        return True
    return False

def generate_u_shape ( frame, bottom, left, right, direction, position ):
    """
    Impose an U shape structure on the frame, position is where you start it (top-left corner of rectangle)
    
    This is an U-shape with bottom = 4, left = 4, right = 3, direction = 0
    S
    o x x o
    o x x o
    o o o o
    
    S o o o 
    o x x 
    o x x 
    o o o
    
    S o o o
    o x x o
    o x x o
    o 
    
    # Let consider this case in a later phase
    This is an U-shape with bottom = 4, left = 4, right = 3, direction = 1
    
            o
          o
        o x
      o x x x
        o x x x o
          o x o
            o
    We can start with even direction first ( 0 (North), 2 (East), 4 (South), 6(West) )
    The positions marked with x are the positions that are considered inside the U-shape
    
    This function returns whether imposition successes, and frame would be imposed with the U-shape
    
    Parameters:
    =====================
    frame: squared frame
    bottom: integer value
    left: integer value
    right: integer value
    direction: 
    position: tuple of 2
    
    Returns:
    =====================
    - success: whether imposition successes or not
    - inside_points: list of points inside the shape (x)
    
    """
    size = frame.shape[0]
    
    other_corner = ( position[0] + max(left, right) - 1, position[1] + bottom - 1 )

    if not check_in_frame ( size, position) or not check_in_frame ( size, other_corner ):
        return False, ( [], [] )
    
    # Let's create one U-shape that has a direction == 0, than we rotate it
    inner_shape = np.zeros((max(left, right), bottom))
    # Left side
    for i in range (max(left, right)):
        inner_shape[i,0] = 1
    
    # Right side
    for i in range (max(left, right) - min(left, right), max(left, right)):
        inner_shape[i,bottom - 1] = 1
    
    # Bottom side
    for i in range (bottom):
        inner_shape[max(left, right) - 1,i] = 1
        
    for i in range(max(left, right) - min(left, right), max(left, right) - 1):
        for j in range(1, bottom - 1):
            inner_shape[i,j] = 2
    
    rotated_shape = np.rot90 ( inner_shape, -direction // 2 )
    
    
    frame[ position[0] : position[0] + rotated_shape.shape[0], 
          position[1] : position[1] + rotated_shape.shape[1] ] = rotated_shape
    
    inside_points = np.where(frame == 2)
    
    frame[frame == 2] = 0
    
    return True, inside_points


In [9]:
def check_in_range (value, bottom, left, right, direction, position ):
    """
    bottom, left, right, direction, position is the parameters of U-shape
    
    value is a coordinates (x, y)
    """
    if direction == 0 or direction == 4:
        if position[0] <= value[0] <= position[0] + max(left, right) and position[1] <= value[1] <= position[1] + bottom:
            return True
    
    if direction == 2 or direction == 6:
        if position[0] <= value[0] <= position[0] + bottom and position[1] <= value[1] <= position[1] +  max(left, right):
            return True
    
    return False

In [6]:
a = np.ones((2,3))
np.where(a == 1)

(array([0, 0, 0, 1, 1, 1], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [7]:
f = zeros ((10, 10))
generate_u_shape (f , 4, 4, 3, 4, (6,5) )

[[1. 0. 0. 0.]
 [1. 2. 2. 1.]
 [1. 2. 2. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 2. 2. 1.]
 [1. 2. 2. 1.]
 [0. 0. 0. 1.]]


(True, (array([7, 7, 8, 8], dtype=int64), array([6, 7, 6, 7], dtype=int64)))

In [8]:
f

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

In [27]:
def generate_env ( size, bottom_range = list(range(3,4)), 
                  left_range = list(range(3,4)), right_range = list(range(3,4)), 
                  direction_range = list(range(0,8,2)) ):
    frame = zeros((size,size))
    
    # You random a value in those range to add into the frame
    # You also
    bottom = choice(bottom_range)
    left = choice(left_range)
    right = choice(right_range)
    direction = choice(direction_range)
    while True:
        position_x = randint ( 0, size - 1 )
        position_y = randint ( 0, size - 1 )
        position = (position_x, position_y)

        success, inner_list = generate_u_shape  ( frame, bottom, left, right, direction, position )
        
        if success : 
            break
    
    # Random outer position for moving point
    while True:
        pos_start_x = randint ( 0, size )
        pos_start_y = randint ( 0, size )
        
        pos_start = (pos_start_x, pos_start_y)
        
        # Just need to be out of the rectangle
        if check_in_range ( pos_start, bottom, left, right, direction, position ):
            continue
            
        break
    
    # Random inner position for moving point
    index = randint ( 0, len(inner_list[0]) )
    pos_end = (inner_list[0][index], inner_list[1][index])
    
    frame[pos_start] = 2
    frame[pos_end] = 3
    
    return frame

In [36]:
generate_env ( 10 )

IndexError: index 10 is out of bounds for axis 1 with size 10