In [13]:
from random import random
from random import randint
from numpy import array
from numpy import zeros
import numpy as np

In [56]:
def check_in_frame ( size, pos ):
    if 0 <= pos[0] < size and  0 <= pos[1] < size:
        return True
    return False

def generate_u_shape ( frame, bottom, left, right, direction, position ):
    """
    Impose an U shape structure on the frame, position is where you start it (top-left corner of rectangle)
    
    This is an U-shape with bottom = 4, left = 4, right = 3, direction = 0
    S
    o x x o
    o x x o
    o o o o
    
    S o o o 
    o x x 
    o x x 
    o o o
    
    S o o o
    o x x o
    o x x o
    o 
    
    # Let consider this case in a later phase
    This is an U-shape with bottom = 4, left = 4, right = 3, direction = 1
    
            o
          o
        o x
      o x x x
        o x x x o
          o x o
            o
    We can start with even direction first ( 0 (North), 2 (East), 4 (South), 6(West) )
    The positions marked with x are the positions that are considered inside the U-shape
    
    This function returns whether imposition successes, and frame would be imposed with the U-shape
    
    Parameters:
    =====================
    frame: squared frame
    bottom: integer value
    left: integer value
    right: integer value
    direction: 
    position: tuple of 2
    
    Returns:
    =====================
    - success: whether imposition successes or not
    - inside_points: list of points inside the shape (x)
    
    """
    size = frame.shape[0]
    
    other_corner = ( position[0] + max(left, right) - 1, position[1] + bottom - 1 )

    if not check_in_frame ( size, position) or not check_in_frame ( size, other_corner ):
        return False, ( [], [] )
    
    # Let's create one U-shape that has a direction == 0, than we rotate it
    inner_shape = np.zeros((max(left, right), bottom))
    # Left side
    for i in range (max(left, right)):
        inner_shape[i,0] = 1
    
    # Right side
    for i in range (max(left, right) - min(left, right), max(left, right)):
        inner_shape[i,bottom - 1] = 1
    
    # Bottom side
    for i in range (bottom):
        inner_shape[max(left, right) - 1,i] = 1
        
    for i in range(max(left, right) - min(left, right), max(left, right) - 1):
        for j in range(1, bottom - 1):
            inner_shape[i,j] = 2
    
    print (inner_shape)
    rotated_shape = np.rot90 ( inner_shape, -direction // 2 )
    
    print (rotated_shape)
    
    frame[ position[0] : position[0] + rotated_shape.shape[0], 
          position[1] : position[1] + rotated_shape.shape[1] ] = rotated_shape
    
    inside_points = np.where(frame == 2)
    
    return True, inside_points


In [57]:
a = np.ones((2,3))
np.where(a == 1)

(array([0, 0, 0, 1, 1, 1], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [64]:
f = zeros ((10, 10))
generate_u_shape (f , 4, 4, 3, 4, (6,5) )

[[1. 0. 0. 0.]
 [1. 2. 2. 1.]
 [1. 2. 2. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 2. 2. 1.]
 [1. 2. 2. 1.]
 [0. 0. 0. 1.]]


(True, (array([7, 7, 8, 8], dtype=int64), array([6, 7, 6, 7], dtype=int64)))

In [65]:
f

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 1., 2., 2., 1., 0.],
       [0., 0., 0., 0., 0., 1., 2., 2., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

In [ ]:
def generate_env ( size, bottom_range = [range(3,4)], left_range = [range(3,4)], right_range = [range(3,4)] ):
    frame = zeros((size,size))
    
    
    
    